name: daily cron job
on:
  schedule:
    - cron: '48 11 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Delete unwatched movies
        run: |
          curl --request GET \
          --url 'http://localhost:3000/api/delete-movie/'