name: daily-cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: macos-mojave
    steps:
      - name: Delete files that are not watched for a month.
        run: |
          curl --request GET \
          --url 'http://localhost:3000/api/delete-movie/'